name: Build

on:
  workflow_dispatch:

jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      # - name: Create ZIP archive
      #   run: |
      #     zip -r linux.zip web main.py requirements.txt

      # - name: Upload to Release
      #   uses: xresloader/upload-to-github-release@v1
      #   with:
      #     file: linux.zip
      #     overwrite: true
      #     update_latest_release: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
